#!/usr/bin/env bash
# script to config domain zone to point to load balancer
# add more subdomains an

function audit_subdomain {
      local domain="$1"
      local subdomain="$2"

      if [ -z "$subdomain" ]; then
	      subdomain=("www" "lb-01" "web-01" "web-02")
      else
	subdomain=("$subdomain")
      fi
      
      for subdomain in "${sub[@]}"; do
	      record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')
	      destination=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ { getline; print $5 }')
	      echo "The subdomain $subdomain is a $record_type record and points to $destination"
      done

}

audit_subdomain "$1" "$2"
